project_name: SustainableUrbanPix2Pix_v3

# -----------------------------
# Training
# -----------------------------
image_size: 256
batch_size: 1
accumulation_steps: 4

epochs: 30                # ✅ FAST FIX TRAIN
lr: 0.0001               # 🔥 slightly higher (important after fixing dataset)

# -----------------------------
# Loss
# -----------------------------
lambda_l1: 70          # reduce from 120 → prevents identity mapping
lambda_perc: 10          # reduce slightly

# -----------------------------
# Model
# -----------------------------
ngf: 32
ndf: 64

# -----------------------------
# Paths
# -----------------------------
checkpoint_dir: outputs/checkpoints
sample_dir: outputs/samples
log_dir: outputs/logs
result_dir: outputs/results

# -----------------------------
# Resume
# -----------------------------
resume_checkpoint: checkpoint_final.pth

# -----------------------------
# Optimization
# -----------------------------
use_amp: true
grad_accumulation: true

# -----------------------------
# Perceptual Loss
# -----------------------------
use_perceptual_loss: false   # 🔥 TURN OFF FOR NOW